USE giantmarket_db;

insert into category values (1, "unico");
insert into category values (2, "varios");
select * from category;
insert into products values (1,"Torre Eiffel","Por si te quieres dar un regalito, este pequeño capricho puede ser tuyo","Un pequeño souvenir, que te quedara de recuerdo. La Torre Eiffel (Tour Eiffel, en francés), inicialmente llamada Tour de 300 mètres (Torre de 300 metros) es una estructura de hierro pudelado diseñada inicialmente por los ingenieros civiles Maurice Koechlin y Émile Nouguier y construida, tras el rediseño estético de Stephen Sauvestre, por el ingeniero civil francés Alexandre Gustave Eiffel y sus colaboradores para la Exposición Universal de 1889 en París.  del Campo de Marte a la orilla del río Sena, este monumento parisino, símbolo de Francia y de su capital, es la estructura más alta de la ciudad Situada en el extremo y el monumento que cobra entrada más visitado del mundo, con 7,1 millones de turistas cada año. Con una altura de 300 metros, prolongada más tarde con una antena hasta los 324 metros, la torre Eiffel fue la estructura más elevada del mundo durante 41 años. Fue construida en dos años, dos meses y cinco días, y en su momento generó cierta controversia entre los artistas de la época, que la veían como un monstruo de hierro. Tras finalizar su función como parte de las Exposiciones Universales de 1889 y 1900, fue utilizada en pruebas del ejército francés con antenas de comunicación, y hoy en día sirve, además de atractivo turístico, como emisora de programas radiofónicos y televisivos. El 15 de marzo de 2022 se sustituyó la antena de radio con la ayuda de un helicóptero, pasando de 324 a 330 m de altura total", 252351092, 48, "1","/images/products/thumbnailTower.jpg","n",0,1);
insert into products values (2,"Google","El motor de busqueda mas grande del planeta. Con esto podrias controlar toda la informacion a tu favor","descripcion", 662287503.81,22,1,"/images/products/thumbnailGoogle.png","n",0,1);
insert into products values(3,"Twitter","Articulo no disponible. (En negociacion con Elon Musk)","descripcion1",44000000,67,1,"/images/products/thumbnailTwitter.png","n",0,1);
insert into products values(4,"McDonald's","Cada que vayas a cualquier McDonald's del mundo tendras acceso a todo el menu para ti.","McDonald's es una franquicia de restaurantes de comida rápida estadounidense con sede en Chicago, Illinois. Sus principales productos son las hamburguesas, las patatas fritas, los menús para el desayuno y los refrescos. También se encuentra una oferta disponible de batidos, helados, postres y, recientemente, ensaladas de fruta o de verdura (así como otros productos exclusivos dependiendo del país). Atiende aproximadamente a 68 millones de clientes por día, en más de 36.000 establecimientos de 118 territorios y países alrededor del mundo. La cadena empleó en 2014 a 1,7 millones de personas. Por otra parte, en la mayoría de los restaurantes, se han incluido distintas zonas de juegos para niños.",929919481.18,10,1,"/images/products/mcdonalds.jpg","n",0,1);
insert into products values(5,"Polo norte","Si estas cansado del calor del verano, nada te impedira venir y disfrutar de tu propio Polo norte.","El polo norte es sustancialmente más caliente que el polo sur, ya que se encuentra a nivel del mar en medio de un océano (que actúa como un reservorio de calor), en lugar de en la altura de una masa de tierra continental. En invierno (enero) las temperaturas en el polo norte pueden variar de aproximadamente de -43 °C a -26 °C, tal vez con un promedio de alrededor de -34 °C. Las temperaturas de verano (junio, julio y agosto) en promedio son alrededor del punto de congelación (0 °C). La temperatura más alta registrada hasta ahora es de 7,2 °C, mucho más caliente que el récord de solo -12.3 °C del polo sur. El hielo marino en el polo norte es típicamente de alrededor de 2 a 3 m de espesor, aunque el espesor del hielo, su extensión espacial y la fracción de aguas abiertas dentro de la bolsa de hielo pueden variar rápida y profundamente en respuesta al tiempo y el clima.",928819356.27,7,1,"/images/products/northpole.jpg","n",0,1);
insert into products values(6,"Ferrari J50","Exclusivo vehiculo de la marca Ferrari","Un exclusivo Ferrari J50, del que únicamente se han fabricado 10 unidades, sale a la venta por casi 3 millones de euros. El Ferrari J50 es una de las ediciones especiales más raras y atractivas lanzadas por la firma de Maranello en los últimos tiempos.",89173155.19,92,2,"/images/products/ferrarij50.jpg","y",6340,10);
insert into products values(7,"Rolex Submariner 'Kermit' ","consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum","El 2003 fue un año muy especial: marcó el 50.º aniversario del legendario Rolex Submariner, el reloj que impulsó a Rolex a alcanzar una duradera fama mundial. El fabricante suizo aprovechó la ocasión para presentar una variante especial con bisel verde del legendario reloj de buceo. En este caso, el color del bisel era algo realmente significativo, pues, aparte de que el verde representa a la marca Rolex, con el Rolex Submariner «Kermit» la casa creó por primera vez un Submariner de acero con bisel de color. Las referencias anteriores de acero del Rolex Submariner siempre se habían mantenido completamente en negro. ",50000,12,2,"/images/products/rolex-kermit-versions.png","y",8480,3);
insert into products values(8,"Café Kopi Luwak 3.5 oz","Es el café más costoso, pero también el más peculiar.","Procedente de Indonesia, el Kopi Luwak se obtiene moliendo los granos de café extraídos de las heces de un animal, la civeta (luwak en el idioma local), que se alimenta casi exclusivamente de bayas de café. Lo mejor, sin embargo, es que estos animales tienen la habilidad de elegir las bayas en su mejor momento de madurez. Las civetas ingieren las bayas y digieren su pulpa, pero no los grano s, eliminándose enteros, lo que facilita la recolección a través de las heces, para luego ser tostados de manera natural (la higiene está garantizada durante todo el proceso de elaboración). Además, que los granos pasen por el aparato digestivo de las civetas tiene sus beneficios, y es que las enzimas del tracto intestinal del animal son capaces de eliminar gran parte de su amargor, lo que lo convierte en una bebida bastante dulce, si la comparamos con otros cafés.",1800,2,2,"/images/products/kopi.jpg","y",2449,521);
insert into products values(9,"Isla del Caribe","Antigua y Barbuda, Barbados, Cuba, Dominica, Haití, Jamaica, República Dominicana, Granada, San Cristóbal y Nieves, San Vicente y las Granadinas, Santa Lucía y Trinidad y Tobago.","El mar Caribe es uno de los mayores mares interiores del mundo, conectado a través del canal de Yucatán, por el sur , con el golfo de México, y a través del paso de los Vientos y del canal de la Mona, por el norte, con el océano Atlántico. Este mar está localizado en la parte centrooriental de América y según la IHO, su límite oriental, desde la punta de San Diego (isla de Puerto Rico) va hacia el norte a lo largo del mismo meridiano (65°39'O) hasta la línea de 100 brazas, y desde allí hacia el este y hacia el sur, de tal manera que todas las islas, bancos de arena y aguas someras de la Antillas Menores estén incluidas en el mar Caribe. Considerando esto, el mar Caribe baña nueve países continentales y doce países insulares,",70000000,10,2,"/images/products/caribe.jpg","n",0,12);
insert into products values(10,"Cruceros","Viaja por el mundo con estos humildes barcos","Un crucero es un tipo de barco de pasajeros para realizar viajes de placer, cuando el viaje en sí, los servicios del barco, y a veces los diferentes destinos en el camino (es decir, puertos de escala), son parte de la experiencia. El transporte no es solo el propósito del crucero, particularmente en cruceros que devuelve a los pasajeros a su puerto original (conocido como «cruceros de circuito cerrado»). En «cruceros a ninguna parte» o «viajes en ninguna parte», el barco hace tours de 2-3 noches sin ningún puerto de escala. Por el contrario, transatlánticos orientados al transporte hacen viajes en línea y normalmente transportan pasajeros de un punto a otro, en lugar de hacerlo en viajes de ida y vuelta. Tradicionalmente, un transatlántico para un viaje transoceánico será construido a un estándar más alto que un crucero típico, incluyendo mayor francobordo y placas más fuertes para resistir los mares agitados y las condiciones adversas que se encuentran en el océano abierto, como el Atlántico Norte. Los transatlánticos también suelen tener mayores capacidades para combustible, alimentos y otras tiendas para el consumo en viajes largos, en comparación con los cruceros dedicados, pero pocos siguen existiendo, como varios transatlánticos preservados incluyendo el Queen Mary 2, que hace los viajes programados del Atlántico Norte.",20000000,15,2,"/images/products/crucero.jpg","y",6024,536);
insert into products values(11,"Jet privado","Volar en el horario deseado, evitar conexiones incluso en lugares remotos y no soportar largas colas ni masificaciones a la hora de facturar son algunas de las ventajas que ofrece.","Hace algunos años que los altos ejecutivos se sumaron al exclusivo grupo de usuarios de jets privados, imitando a los hombres de negocios americanos. Viajar en el horario deseado, la necesidad de privacidad y seguridad y un servicio altamente personalizado y exclusivo son algunas de las razones que motivan la aviación ejecutiva. Además, mientras que este tipo de público se muestra cada vez más reticente a compartir avión con personas desconocidas, los jets privados y aerotaxis garantizan el anonimato al no existir listas de pasajeros ni anunciar los vuelos en las pantallas de los aeropuertos. Esta necesidad de privacidad y seguridad se hizo evidente tras los atentados del 11-S en Estados Unidos, momento a partir del cual muchos directivos eligieron los aerotaxis para sus desplazamientos. La aviación ejecutiva se considera un privilegio caro y restringido. Por ello, cada vez es más frecuente que los propietarios de aviones privados -ya sean particulares o grandes compañías- subalquilen estas aeronaves a empresas encargadas de la gestión para sacar beneficio a la inversión. Para que un propietario pueda alquilar su avión a terceros debe ceder la explotación comercial de su aeronave a una empresa que disponga de un Certificado de Transporte Aéreo (CTA). Esta forma de optimizar el uso de su avión se traduce en dos modalidades de venta. Una de ellas es el chárter o aerotaxi puntual, que concreta el precio del servicio en función de la ruta requerida y del tipo de avión necesario, variable según la capacidad y el alcance. Pero también es posible comprar un paquete de horas a consumir durante un periodo determinado u optar por la propiedad compartida o fractional ownership mediante la que varios propietarios disponen de una parte de valor del avión",10000000,8,2,"/images/products/jet.jpg","y",6024,251);
insert into products values(12,"Asus","","Fundada en 1989, ASUS es una empresa multinacional conocida por las mejores placas base del mundo y computadoras personales, monitores, tarjetas gráficas, enrutadores y otras soluciones tecnológicas de alta calidad. Hoy, ASUS está diseñando y construyendo tecnologías inteligentes de próxima generación para brindar experiencias increíbles que mejoran la vida de las personas en todas partes.",78000000,2,1,"/images/products/asus.jpg","n",0,1);
insert into products values(13,"Electronic Arts","","Electronic Arts Inc. (EA) es una empresa estadounidense desarrolladora y distribuidora de videojuegos, fundada por Trip Hawkins el 27 de mayo de 1982 en San Mateo, California. Actualmente, desarrolla y publica juegos que incluyen los títulos de EA Sports FIFA, Madden NFL, NHL, NBA Live y UFC. Otras franquicias incluyen Battlefield, Need for Speed, Real Racing, Los Sims, Medal of Honor, Command & Conquer, Dead Space, Mass Effect, Dragon Age, Army of Two, Titanfall y Star Wars: The Old Republic, entre otros. Es el creador de EA App, plataformas de distribución digital de juegos en línea para ordenadores en donde se encuentran todos sus juegos.",45000000,1,1,"/images/products/ea.jpg","n",0,1);
insert into products values(14,"Dolce & Gabbana","","Dolce & Gabbana es una marca de moda de lujo de Italia, fundada en 1985 por Domenico Dolce y Stefano Gabbana. La marca es uno de los nombres icónicos en la historia de la moda y es muy reconocida y amada por muchas celebridades. Dolce & Gabbana es una marca conocida en todo el mundo, es una etiqueta icónica con un rico patrimonio y una historia colorida. La marca fuerte y elegante en todas las letras mayúsculas se ejecuta en una fuente Futura tradicional, que es uno de los tipos de letra más utilizados para la industria de la moda, debido a sus líneas simples pero fuertes y formas modestas. Aunque inicialmente comenzaron diseñando ropa, actualmente la empresa ha diversificado su oferta diseñando desde complementos (gafas, relojes, anillos, etc.) y perfumes a móviles (V3 de Dolce & Gabbana) o incluso restaurantes.",653313510.08,45,1,"/images/products/dyc.png","n",0,1);
insert into products values(15,"Hollywood","¡Has tus propias peliculas!","Hollywood es un barrio de la ciudad de Los Ángeles, California, Estados Unidos, que se ha convertido en una metonimia de la industria cinematográfica estadounidense. Muchos de sus estudios, como los de Columbia Pictures, Disney, Paramount Pictures, la Warner Bros. o Universal Pictures, fueron fundados aquí; Paramount todavía tiene sus estudios en este barrio. Hollywood fue fundado como municipio en 1903 En 1910, se fusionó con la ciudad de Los Ángeles y, poco después, surgió una importante industria cinematográfica que, finalmente, se convertiría en la más conocida del mundo.",94719660.6,0,1,"/images/products/hollywood.jpg","n",0,1);
insert into products values(16,"Mona Lisa","Un cuadro que podras colocar en el baño de tu casa","El retrato de Lisa Gherardini, esposa de Francesco del Giocondo, más conocido como La Gioconda (La Joconde en francés) o Monna Lisa, es una obra pictórica del polímata renacentista italiano Leonardo da Vinci. Fue adquirida por el rey Francisco I de Francia a comienzos del siglo XVI y desde entonces es propiedad del Estado francés. Se halla expuesta en el Museo del Louvre de París, siendo, sin duda, la «joya» de sus colecciones.",900000000,0,1,"/images/products/image-1654455806757-202105914.jpg","y",10000,1);

select * from products;

insert into roles values(1,'Adimistrador');
insert into roles values(2,'Usuario');

select * from roles;

insert into users values (1,"Cristal","Ogilby","ayuda@gmail.com","Female","2086/4/24","11111111",1,"default-image.png");
insert into users values (2,"Gertrude","Championnet","ayuda1@gmail.com","Female","1984/10/11","12345678",2,"default-image.png");
insert into users values (3,"Yoshi","Impy","sos@gmail.com","Female","1984/10/11","12345678",1,"default-image.png");
insert into users values (4,"Shay","Bickley","ayudasos@gmail.com","Female","2086/4/24","12345678",2,"default-image.png");
insert into users values (5,"Costa","Lavis","clavis4@epa.gov","Male","1997/9/21","12345678",2,"default-image.png");
insert into users values (6,"Ansell","Tremmil","atremmil5@flickr.com","Polygender","2086/4/24","YJp9EwgH",2,"default-image.png");
insert into users values (7,"Karine","Tims","ktims6@hatena.ne.jp","Female","1997/9/21","wf5wbdn",2,"default-image.png");
insert into users values (8,"Christiano","Gallichan","cgallichan7@google.fr","Male","1997/9/21","UEdVh87q",2,"default-image.png");
insert into users values (9,"Dave","Barreau","dbarreau8@hhs.gov","Male","1997/9/21","12345678",2,"default-image.png");
insert into users values (10,"Sam","Slateford","sslateford9@foxnews.com","Male","1997/9/21","abc42136",2,"default-image.png");


select * from users;